#!/bin/sh

ENABLED=yes

DESC="Fail2Ban server"
PROCS="fail2ban-server"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/fail2ban/fail2ban.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-xf start"
PREARGS=""

. /opt/etc/init.d/rc.func
