#!/bin/sh

ENABLED=yes

DESC="OpenLDAP Server Daemon"
PROCS="slapd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/openldap-data" ] || \
  mkdir -pm 0700 /opt/var/lib/openldap-data
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
