#!/bin/sh

ENABLED=yes

DESC="Layer 2 Tunneling Protocol daemon"
PROCS="xl2tpd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/run/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/run/"$PROCS"
  [ -n "$(iptables-save | grep 'udp --dport 1701')" ] || \
  iptables -I INPUT -p udp --dport 1701 -j ACCEPT
}

PRECMD="start_pre"
ARGS="-p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
