#!/bin/sh

ENABLED=yes

DESC="CUPS daemon"
PROCS="cupsd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/cups/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  . /opt/lib/functions.sh
  group_exists lpadmin || group_add lpadmin 115
  group_exists sys || group_add sys 3
  user_exists lpadmin || user_add lpadmin 115
  user_exists sys || user_add sys 3
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
