#!/bin/sh

ENABLED=yes

DESC="Tang daemon"
PROCS="tangd"
PROG="/opt/sbin/$PROCS"

TANG_DB_DIR="/opt/share/tang/db"

start_pre() {
  [ -d "$TANG_DB_DIR" ] || mkdir -pm 0750 "$TANG_DB_DIR"
  KEYS=$(find "$TANG_DB_DIR" -maxdepth 1 -name "*.jw*" 2>/dev/null | wc -l)
  if [ -z "${KEYS}" ] || [ "${KEYS}" = "0" ]; then # if db is empty generate new key pair
    "$PROG"-keygen "$TANG_DB_DIR"
  fi
  chown -R tang "$TANG_DB_DIR"
}

PRECMD="start_pre"
ARGS="-p 9090 -l $TANG_DB_DIR"
PREARGS=""

. /opt/etc/init.d/rc.func
