#!/bin/sh

ENABLED=yes

DESC="D-Bus daemon"
PROCS="dbus-daemon"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/dbus/dbus.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/run/dbus" ] || \
  mkdir -pm 0750 /opt/var/run/dbus
}

PRECMD="start_pre"
ARGS="--system"
PREARGS=""

. /opt/etc/init.d/rc.func
