#!/bin/sh

ENABLED=yes

DESC="OpenVPN"
PROCS="openvpn"
PROG="/opt/sbin/$PROCS"

start_pre() {
# Make sure IP forwarding is enabled
  grep -q '1' /proc/sys/net/ipv4/ip_forward || \
  echo 1 > /proc/sys/net/ipv4/ip_forward

# Make /dev/net directory if needed
# Make device if not present (not devfs)
  { [ -d "/dev/net" ] || mkdir -pm 0755 /dev/net ; } || \
  { [ -c "/dev/net/tun" ] || mknod /dev/net/tun c 10 200 ; }

# Make sure the tunnel driver is loaded
#if ( !(lsmod | grep -q "^tun") ); then
#	insmod /opt/lib/modules/tun.ko
#fi
}

PRECMD="start_pre"
ARGS="--daemon --cd /opt/etc/$PROCS --config $PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
