#!/bin/sh

ENABLED=yes

DESC="HTTP and HTTPS proxy"
PROCS="tinyproxy"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-c /opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
