#!/bin/sh

ENABLED=yes

DESC="vnStat (2) daemon"
PROCS="vnstatd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -f "/opt/var/lib/vnstat/vnstat.db" ] || {
  "$PROG" --initdb
  for i in $(ls -1 /sys/class/net)
  do
    [ -n "$(vnstat --dbiflist | grep -q $i)" ] || {
      /opt/bin/vnstat --add --force -i "$i" > /dev/null
    }
  done
  }
}

PRECMD="start_pre"
ARGS="-d -p $PID_FILE --noadd --startempty --noremove"
PREARGS=""

. /opt/etc/init.d/rc.func
