#!/bin/sh

ENABLED=yes

DESC="USB-over-IP"
PROCS="usbipd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-D -PFILE $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
