#!/bin/sh

ENABLED=yes

DESC="PC/SC daemon"
PROCS="pcscd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
