#!/bin/sh

ENABLED=yes

DESC="MariaDB server"
PROCS="mysqld"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"
LIMIT="20"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/run/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/run/"$PROCS"
  [ -d "/opt/srv/mysql" ] || \
  mysql_install_db --force --basedir=/opt --skip-test-db \
  --datadir=/opt/srv/mysql > /dev/null 2>&1
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
