#!/bin/sh

ENABLED=yes

DESC="HAVEGE daemon"
PROCS="haveged"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="-w 1024 -d 32 -i 32 -v 1 -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
