#!/bin/sh

ENABLED=yes

DESC="vnStat daemon"
PROCS="vnstatd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/vnstat" ] || {
  mkdir -pm 0750 /opt/var/lib/vnstat
  for i in $(ls -1 /sys/class/net)
  do
    [ -f "/opt/var/lib/vnstat/$i" ] || {
    /opt/bin/vnstat --create -i "$i" > /dev/null
    }
  done
  }
  /opt/bin/vnstat -u > /dev/null
}

PRECMD="start_pre"
ARGS="-d -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
