#!/bin/sh

ENABLED=yes

DESC="Squid proxy"
PROCS="squid"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/cache/"$PROCS" \
    /opt/var/log/"$PROCS"
  do
    [ -d "$i" ] || {
    mkdir -pm 0750 "$i"
    chown "$PROCS":"$PROCS" "$i"
    }
  done
  if ! grep -qs '/dev/shm' /proc/mounts ; then
    [ -d "/dev/shm" ] || mkdir -p /dev/shm
    mount -t tmpfs -o rw,nosuid,nodev,size=1M tmpfs /dev/shm
  fi
  "$PROG" -n $PROCS -z -N > /dev/null 2>&1
  [ -f "/opt/var/cache/$PROCS/ssldb/size" ] || \
  /opt/lib/"$PROCS"/security_file_certgen -c -s /opt/var/cache/"$PROCS"/ssldb -M 4MB 1>/dev/null
  chown -R "$PROCS":"$PROCS" /opt/var/cache/"$PROCS"/ssldb
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
