#!/bin/sh

ENABLED=yes

DESC="Connection tracking userspace daemon"
PROCS="conntrackd"
PROG="/opt/sbin/$PROCS"

start_pre() {
  rm -f /opt/var/lock/conntrack.lock
}

PRECMD="start_pre"
ARGS="-d -C /opt/etc/$PROCS/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
