#!/bin/sh

ENABLED=yes

DESC="Dante SOCKS"
PROCS="sockd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-f /opt/etc/$PROCS.conf -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
