#!/bin/sh

ENABLED=yes

DESC="Ligttpd server"
PROCS="lighttpd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  . /opt/lib/functions.sh
  group_exists www-data || group_add www-data 33
  for i in \
    /opt/var/cache/"$PROCS" \
    /opt/var/lib/"$PROCS" \
    /opt/var/log/"$PROCS"
  do
    [ -d "$i" ] || {
      mkdir -pm 0775 "$i"
      chgrp www-data "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="-f /opt/etc/$PROCS/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
