#!/bin/sh

ENABLED=yes

DESC="Tor daemon"
PROCS="tor"
PROG="/opt/sbin/$PROCS"

start_pre() {
  [ -d "/opt/var/lib/$PROCS" ] || {
    mkdir -pm 0700 /opt/var/lib/"$PROCS"
    chown -R "$PROCS":"$PROCS" /opt/var/lib/"$PROCS"
  }

  [ -d "/opt/var/log/$PROCS" ] || {
    mkdir -pm 0755  /opt/var/log/"$PROCS"
    chown -R "$PROCS":"$PROCS" /opt/var/log/"$PROCS"
  }
}

PRECMD="start_pre"
ARGS="-f /opt/etc/$PROCS/torrc"
PREARGS=""

. /opt/etc/init.d/rc.func
