#!/bin/sh

ENABLED=yes

DESC="SNMP notification receiver"
PROCS="snmptrapd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="-Lf /dev/null -p $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
