#!/bin/sh

ENABLED=yes

DESC="System statistics collection daemon"
PROCS="collectd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-C /opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
