#!/bin/sh

ENABLED=yes

DESC="SSL/SSH multiplexer"
PROCS="sslh"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-F /opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
