#!/bin/sh

ENABLED=yes

DESC="Aria2 service"
PROCS="aria2c"
PROG="/opt/bin/$PROCS"

start_pre() {
  for i in \
    /opt/downloads/aria2 \
    /opt/var/lib/aria2
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chown -R aria2:aria2 "$i"
    }
  done
  [ -e /opt/var/lib/aria2/session.dat ] || \
  touch /opt/var/lib/aria2/session.dat
  chown -R aria2:aria2 /opt/var/lib/aria2/session.dat
}

PRECMD="start_pre"
ARGS="--conf-path=/opt/etc/aria2.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
