#!/bin/sh

ENABLED=yes

DESC="Serial to Network Proxy"
PROCS="ser2net"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="-P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
