#!/bin/sh

ENABLED=yes

DESC="Avahi daemon"
PROCS="avahi-daemon"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-D"
PREARGS=""

. /opt/etc/init.d/rc.func
