#!/bin/sh

ENABLED=yes

DESC="PulseAudio server"
PROCS="pulseaudio"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/pulse/pid"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/lib/pulse \
    /opt/var/run/pulse
  do
    [ -d "$i" ] || {
      mkdir -pm 0700 "$i"
      chown pulse:pulse "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="\
--system \
--daemonize \
--disallow-module-loading \
--disallow-exit \
--exit-idle-time=-1 \
--use-pid-file \
--disable-shm"
PREARGS=""

. /opt/etc/init.d/rc.func
