#!/bin/sh

ENABLED=yes

DESC="SMS Server Tools daemon"
PROCS="smsd"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/spool/sms \
    /opt/var/spool/sms/checked \
    /opt/var/spool/sms/failed \
    /opt/var/spool/sms/incoming \
    /opt/var/spool/sms/outgoing \
    /opt/var/spool/sms/sent
  do
    [ -d "$i" ] || mkdir -pm 0750 "$i"
  done
}

PRECMD="start_pre"
ARGS="-p$PID_FILE -i/opt/var/run/$PROCS.working"
PREARGS=""

. /opt/etc/init.d/rc.func
