#!/bin/sh

ENABLED=yes

DESC="Single Packet Authorization server"
PROCS="fwknopd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
#  [ -d "/opt/var/lib/$PROCS" ] || \
#  mkdir -pm 0700 /opt/var/lib/"$PROCS"
  if ! lsmod | grep -q xt_comment ; then
    insmod /lib/modules/$(uname -r)/xt_comment.ko
  fi
}

PRECMD="start_pre"
ARGS="-c /opt/etc/fwknop/$PROCS.conf -p $PID_FILE -r /opt/var/lib/$PROCS"
PREARGS=""

. /opt/etc/init.d/rc.func
