#!/bin/sh

ENABLED=yes

DESC="ZNC"
PROCS="znc"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/run/$PROCS" ] || {
    mkdir -pm 0750 /opt/var/run/"$PROCS"
    chown -Rh "$PROCS":"$PROCS" /opt/share/"$PROCS" /opt/var/run/"$PROCS"
  }
}

PRECMD="start_pre"
ARGS="-d /opt/share/$PROCS -r"
PREARGS=""

. /opt/etc/init.d/rc.func
