#!/bin/sh

ENABLED=yes

DESC="DNS server"
PROCS="named"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS/$PROCS.pid"

start_pre() {
  for i in \
    /opt/var/cache/bind \
    /opt/var/lib/bind \
    /opt/var/log/$PROCS \
    /opt/var/run/$PROCS
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chown bind:bind "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="-u bind -c /opt/etc/bind/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
