#!/bin/sh

ENABLED=yes

DESC="Rsync daemon"
PROCS="rsync"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="--daemon --config=/opt/etc/rsyncd.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
