#!/bin/sh

ENABLED=yes

DESC="NTP client and server"
PROCS="chronyd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/chrony/$PROCS.pid"

start_pre() {
  rm -f "$PIF_FILE"
  for i in \
    /opt/var/lib/chrony \
    /opt/var/log/chrony \
    /opt/var/run/chrony
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chgrp chrony "$i"
    }
  done
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
