#!/bin/sh

ENABLED=yes

DESC="Netdata monitoring tool"
PROCS="netdata"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/cache/"$PROCS" \
    /opt/var/lib/"$PROCS" \
    /opt/var/log/"$PROCS"
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chown nobody "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="-P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
