#!/bin/sh

ENABLED=yes

DESC="Motion service"
PROCS="motion"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-b -p $PID_FILE -c /opt/etc/$PROCS/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
