#!/bin/sh

ENABLED=yes

DESC="atd daemon"
PROCS="atd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/spool/cron/atjobs \
    /opt/var/spool/cron/atspool
  do
    [ -d "$i" ] || {
      mkdir -pm 0755 "$i"
      chown -R nobody:nogroup "$i"
    }
  done
  [ -f "/opt/var/spool/cron/atjobs/.SEQ" ] || {
    touch /opt/var/spool/cron/atjobs/.SEQ
    chown -R nobody:nogroup /opt/var/spool/cron/atjobs/.SEQ
  }
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
