#!/bin/sh

ENABLED=yes

DESC="ISC NTP daemon"
PROCS="ntpd"
PROG="/opt/sbin/$PROCS"

{ [ -f "/opt/etc/config/$PROCS.conf" ] && . /opt/etc/config/"$PROCS".conf ; } || \
{ printf "\033[1;31m %s \033[0m\n" "Abort: conf file not found." && exit 1 ; }

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  for i in \
    /opt/var/lib/ntp \
    /opt/var/spool/ntp
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chown ntp:ntp "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="\
-c /opt/etc/ntp.conf \
-f /opt/var/lib/ntp/ntp.drift \
-p $PID_FILE \
-s /opt/var/spool/ntp \
-k /opt/etc/ntp \
-g $OPTIONS"
PREARGS=""

. /opt/etc/init.d/rc.func
