#!/bin/sh

ENABLED=yes

DESC="Zabbix agent daemon"
PROCS="zabbix_agentd"
PROG="/opt/sbin/$PROCS"

start_pre() {
  . /opt/lib/functions.sh
  user_exists zabbix-agent || user_add zabbix-agent 53
  group_exists zabbix-agent || group_add zabbix-agent 53
  {
    { [ -d "/opt/var/log/zabbix" ] || \
    mkdir -pm 0750 /opt/var/log/zabbix ; }
    chown -R zabbix-agent:zabbix-agent /opt/var/log/zabbix ;
  }
}

PRECMD="start_pre"
ARGS="-c /opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
